### PR TITLE
Only allow numbers in streetNumber string

### PR DESCRIPTION
**Pull request by odynvolk**
**Checklist**

- [ ] Was the code tested in lab?
- [x] Have you reviewed the code yourself?
- [x] Are the configs updated?
- [x] Does the readme need an update?

## Write the description and the reason for this PR below ↓
Currently we're allowing streetNumber to have values as "1A", which should be streetNumber 1, stairCase A. This causes problems at distribution innovation later on.

This a one part of the fixes needed here.

https://favro.com/organization/a75be0396fe39314c7ac300f/fdaea1f08a3e304708565fd5?card=Bon-166377

### CODE REVIEW

**Review by MattiasOlla — COMMENTED** [review]
Ska vi inte tillåta `Testgatan 1A`? Känns som en ganska vanlig grej i adresser?

**Comment by varney** [comment]
> Ska vi inte tillåta `Testgatan 1A`? Känns som en ganska vanlig grej i adresser?

Det ska egentligen vara `streetName: Testgatan, streetNumber: 1, stairCase: A` - så nej, `streetNumber: 1A` ska inte tillåtas.

**Review by varney — CHANGES_REQUESTED** [review]
The problem is that not all streetNumbers are just numbers. There are some addresses out in the country that have an alphabetic streetNumber, and others that have e.g. `-39` which is also legitimate.

Perhaps restricting to:
- only numeric, OR
- only numeric with leading `-`, OR
- only alphabetic

would be better.

**Comment by odynvolk** [comment]
> The problem is that not all streetNumbers are just numbers. There are some addresses out in the country that have an alphabetic streetNumber, and others that have e.g. `-39` which is also legitimate.
> 
> Perhaps restricting to:
> 
> * only numeric, OR
> * only numeric with leading `-`, OR
> * only alphabetic
> 
> would be better.

Ah OK! Will fix! Update coming later today.

**Review by varney — APPROVED** [review]
👍 

Oh how I dislike weird addresses.

**Pull request merged**
